export const CountryCodes = [
    {
        name: "United States",
        code: "US",
        continent: "North America",
        flag: "https://flagcdn.com/us.svg",
        dial_code: "+1",
    },
    {
        name: "Canada",
        code: "CA",
        continent: "North America",
        flag: "https://flagcdn.com/ca.svg",
        dial_code: "+1",
    },
    {
        name: "Mexico",
        code: "MX",
        continent: "North America",
        flag: "https://flagcdn.com/mx.svg",
        dial_code: "+52",
    },
    {
        name: "Brazil",
        code: "BR",
        continent: "South America",
        flag: "https://flagcdn.com/br.svg",
        dial_code: "+55",
    },
    {
        name: "Argentina",
        code: "AR",
        continent: "South America",
        flag: "https://flagcdn.com/ar.svg",
        dial_code: "+54",
    },
    {
        name: "United Kingdom",
        code: "GB",
        continent: "Europe",
        flag: "https://flagcdn.com/gb.svg",
        dial_code: "+44",
    },
    {
        name: "Germany",
        code: "DE",
        continent: "Europe",
        flag: "https://flagcdn.com/de.svg",
        dial_code: "+49",
    },
    {
        name: "France",
        code: "FR",
        continent: "Europe",
        flag: "https://flagcdn.com/fr.svg",
        dial_code: "+33",
    },
    {
        name: "Italy",
        code: "IT",
        continent: "Europe",
        flag: "https://flagcdn.com/it.svg",
        dial_code: "+39",
    },
    {
        name: "Spain",
        code: "ES",
        continent: "Europe",
        flag: "https://flagcdn.com/es.svg",
        dial_code: "+34",
    },
    {
        name: "China",
        code: "CN",
        continent: "Asia",
        flag: "https://flagcdn.com/cn.svg",
        dial_code: "+86",
    },
    {
        name: "India",
        code: "IN",
        continent: "Asia",
        flag: "https://flagcdn.com/in.svg",
        dial_code: "+91",
    },
    {
        name: "Japan",
        code: "JP",
        continent: "Asia",
        flag: "https://flagcdn.com/jp.svg",
        dial_code: "+81",
    },
    {
        name: "South Korea",
        code: "KR",
        continent: "Asia",
        flag: "https://flagcdn.com/kr.svg",
        dial_code: "+82",
    },
    {
        name: "Indonesia",
        code: "ID",
        continent: "Asia",
        flag: "https://flagcdn.com/id.svg",
        dial_code: "+62",
    },
    {
        name: "Nigeria",
        code: "NG",
        continent: "Africa",
        flag: "https://flagcdn.com/ng.svg",
        dial_code: "+234",
    },
    {
        name: "South Africa",
        code: "ZA",
        continent: "Africa",
        flag: "https://flagcdn.com/za.svg",
        dial_code: "+27",
    },
    {
        name: "Egypt",
        code: "EG",
        continent: "Africa",
        flag: "https://flagcdn.com/eg.svg",
        dial_code: "+20",
    },
    {
        name: "Australia",
        code: "AU",
        continent: "Oceania",
        flag: "https://flagcdn.com/au.svg",
        dial_code: "+61",
    },
    {
        name: "New Zealand",
        code: "NZ",
        continent: "Oceania",
        flag: "https://flagcdn.com/nz.svg",
        dial_code: "+64",
    },
];
