export const industries = [
    "Technology",
    "Health",
    "Media",
    "Sport",
    "Business",
    "Commerce",
    "Manufacturing",
    "Entertainment",
    "Government",
    "Construction",
    "Transportation",
    "Agriculture",
    "Banking",
    "Education",
    "Others",
  ];